
--[[
Input Mappings file
This creates all the mappings from various code-names of Tara input to the number
representing the input value in the underlying system

These numbers are intentionally the EXACT SAME and a similar name to GLFW, to make everything
easier for both me as engine programmer, as well as making the engine faster
--]]

--[[
Joystick Hat Positions (ie, where a joystick is moved to
--]]
TARA_JOYSTICK_HAT_CENTERED=0
TARA_JOYSTICK_HAT_UP=1
TARA_JOYSTICK_HAT_RIGHT=2
TARA_JOYSTICK_HAT_DOWN=4
TARA_JOYSTICK_HAT_LEFT=8
TARA_JOYSTICK_HAT_RIGHT_UP=(TARA_JOYSTICK_HAT_RIGHT | TARA_JOYSTICK_HAT_UP)
TARA_JOYSTICK_HAT_RIGHT_DOWN=(TARA_JOYSTICK_HAT_RIGHT | TARA_JOYSTICK_HAT_DOWN)
TARA_JOYSTICK_HAT_LEFT_UP=(TARA_JOYSTICK_HAT_LEFT  | TARA_JOYSTICK_HAT_UP)
TARA_JOYSTICK_HAT_LEFT_DOWN=(TARA_JOYSTICK_HAT_LEFT  | TARA_JOYSTICK_HAT_DOWN)

--[[Key codes--]]
--[[ The unknown key --]]
TARA_KEY_UNKNOWN=-1

--[[ 
Printable keys 
Many of these match their ASCII characters. To make things easier.
--]]
TARA_KEY_SPACE=32
TARA_KEY_APOSTROPHE=39  --[[ ' --]]
TARA_KEY_COMMA=44  --[[ , --]]
TARA_KEY_MINUS=45  --[[ - --]]
TARA_KEY_PERIOD=46  --[[ . --]]
TARA_KEY_SLASH=47  --[[ / --]]
TARA_KEY_0=48
TARA_KEY_1=49
TARA_KEY_2=50
TARA_KEY_3=51
TARA_KEY_4=52
TARA_KEY_5=53
TARA_KEY_6=54
TARA_KEY_7=55
TARA_KEY_8=56
TARA_KEY_9=57
TARA_KEY_SEMICOLON=59  --[[ ; --]]
TARA_KEY_EQUAL=61  --[[ = --]]
TARA_KEY_A=65
TARA_KEY_B=66
TARA_KEY_C=67
TARA_KEY_D=68
TARA_KEY_E=69
TARA_KEY_F=70
TARA_KEY_G=71
TARA_KEY_H=72
TARA_KEY_I=73
TARA_KEY_J=74
TARA_KEY_K=75
TARA_KEY_L=76
TARA_KEY_M=77
TARA_KEY_N=78
TARA_KEY_O=79
TARA_KEY_P=80
TARA_KEY_Q=81
TARA_KEY_R=82
TARA_KEY_S=83
TARA_KEY_T=84
TARA_KEY_U=85
TARA_KEY_V=86
TARA_KEY_W=87
TARA_KEY_X=88
TARA_KEY_Y=89
TARA_KEY_Z=90
TARA_KEY_LEFT_BRACKET=91  --[[ [ --]]
TARA_KEY_BACKSLASH=92  --[[ \ --]]
TARA_KEY_RIGHT_BRACKET=93  --[[ ] --]]
TARA_KEY_GRAVE_ACCENT=96  --[[ ` --]]
TARA_KEY_WORLD_1=161 --[[ non-US #1 --]]
TARA_KEY_WORLD_2=162 --[[ non-US #2 --]]

--[[ 
Function keys 
These are ALL larger than a char, and thus clearly not ASCII
--]]
TARA_KEY_ESCAPE=256
TARA_KEY_ENTER=257
TARA_KEY_TAB=258
TARA_KEY_BACKSPACE=259
TARA_KEY_INSERT=260
TARA_KEY_DELETE=261
TARA_KEY_RIGHT=262
TARA_KEY_LEFT=263
TARA_KEY_DOWN=264
TARA_KEY_UP=265
TARA_KEY_PAGE_UP=266
TARA_KEY_PAGE_DOWN=267
TARA_KEY_HOME=268
TARA_KEY_END=269
TARA_KEY_CAPS_LOCK=280
TARA_KEY_SCROLL_LOCK=281
TARA_KEY_NUM_LOCK=282
TARA_KEY_PRINT_SCREEN=283
TARA_KEY_PAUSE=284
TARA_KEY_F1=290
TARA_KEY_F2=291
TARA_KEY_F3=292
TARA_KEY_F4=293
TARA_KEY_F5=294
TARA_KEY_F6=295
TARA_KEY_F7=296
TARA_KEY_F8=297
TARA_KEY_F9=298
TARA_KEY_F10=299
TARA_KEY_F11=300
TARA_KEY_F12=301
TARA_KEY_F13=302
TARA_KEY_F14=303
TARA_KEY_F15=304
TARA_KEY_F16=305
TARA_KEY_F17=306
TARA_KEY_F18=307
TARA_KEY_F19=308
TARA_KEY_F20=309
TARA_KEY_F21=310
TARA_KEY_F22=311
TARA_KEY_F23=312
TARA_KEY_F24=313
TARA_KEY_F25=314
TARA_KEY_KP_0=320
TARA_KEY_KP_1=321
TARA_KEY_KP_2=322
TARA_KEY_KP_3=323
TARA_KEY_KP_4=324
TARA_KEY_KP_5=325
TARA_KEY_KP_6=326
TARA_KEY_KP_7=327
TARA_KEY_KP_8=328
TARA_KEY_KP_9=329
TARA_KEY_KP_DECIMAL=330
TARA_KEY_KP_DIVIDE=331
TARA_KEY_KP_MULTIPLY=332
TARA_KEY_KP_SUBTRACT=333
TARA_KEY_KP_ADD=334
TARA_KEY_KP_ENTER=335
TARA_KEY_KP_EQUAL=336
TARA_KEY_LEFT_SHIFT=340
TARA_KEY_LEFT_CONTROL=341
TARA_KEY_LEFT_ALT=342
TARA_KEY_LEFT_SUPER=343
TARA_KEY_RIGHT_SHIFT=344
TARA_KEY_RIGHT_CONTROL=345
TARA_KEY_RIGHT_ALT=346
TARA_KEY_RIGHT_SUPER=347
TARA_KEY_MENU=348

TARA_KEY_LAST=TARA_KEY_MENU


--[[
Modifier key bits
used in modifer checks. Each one is a bit
--]]
TARA_MOD_SHIFT=0x0001
TARA_MOD_CONTROL=0x0002
TARA_MOD_ALT=0x0004
TARA_MOD_SUPER=0x0008
TARA_MOD_CAPS_LOCK=0x0010
TARA_MOD_NUM_LOCK=0x0020

--[[
Mouse Button Codes
--]]
TARA_MOUSE_BUTTON_1=0
TARA_MOUSE_BUTTON_2=1
TARA_MOUSE_BUTTON_3=2
TARA_MOUSE_BUTTON_4=3
TARA_MOUSE_BUTTON_5=4
TARA_MOUSE_BUTTON_6=5
TARA_MOUSE_BUTTON_7=6
TARA_MOUSE_BUTTON_8=7
TARA_MOUSE_BUTTON_LAST=TARA_MOUSE_BUTTON_8
TARA_MOUSE_BUTTON_LEFT=TARA_MOUSE_BUTTON_1
TARA_MOUSE_BUTTON_RIGHT=TARA_MOUSE_BUTTON_2
TARA_MOUSE_BUTTON_MIDDLE=TARA_MOUSE_BUTTON_3

--[[
Joystick Mapping codes
--]]
TARA_JOYSTICK_1=0
TARA_JOYSTICK_2=1
TARA_JOYSTICK_3=2
TARA_JOYSTICK_4=3
TARA_JOYSTICK_5=4
TARA_JOYSTICK_6=5
TARA_JOYSTICK_7=6
TARA_JOYSTICK_8=7
TARA_JOYSTICK_9=8
TARA_JOYSTICK_10=9
TARA_JOYSTICK_11=10
TARA_JOYSTICK_12=11
TARA_JOYSTICK_13=12
TARA_JOYSTICK_14=13
TARA_JOYSTICK_15=14
TARA_JOYSTICK_16=15
TARA_JOYSTICK_LAST=TARA_JOYSTICK_16

--[[
Gamepad mappings
--]]
TARA_GAMEPAD_BUTTON_A=0
TARA_GAMEPAD_BUTTON_B=1
TARA_GAMEPAD_BUTTON_X=2
TARA_GAMEPAD_BUTTON_Y=3
TARA_GAMEPAD_BUTTON_LEFT_BUMPER=4
TARA_GAMEPAD_BUTTON_RIGHT_BUMPER=5
TARA_GAMEPAD_BUTTON_BACK=6
TARA_GAMEPAD_BUTTON_START=7
TARA_GAMEPAD_BUTTON_GUIDE=8
TARA_GAMEPAD_BUTTON_LEFT_THUMB=9
TARA_GAMEPAD_BUTTON_RIGHT_THUMB=10
TARA_GAMEPAD_BUTTON_DPAD_UP=11
TARA_GAMEPAD_BUTTON_DPAD_RIGHT=12
TARA_GAMEPAD_BUTTON_DPAD_DOWN=13
TARA_GAMEPAD_BUTTON_DPAD_LEFT=14
TARA_GAMEPAD_BUTTON_LAST=TARA_GAMEPAD_BUTTON_DPAD_LEFT
--[[
Alias sony buttons as MS buttons
--]]
TARA_GAMEPAD_BUTTON_CROSS=TARA_GAMEPAD_BUTTON_A
TARA_GAMEPAD_BUTTON_CIRCLE=TARA_GAMEPAD_BUTTON_B
TARA_GAMEPAD_BUTTON_SQUARE=TARA_GAMEPAD_BUTTON_X
TARA_GAMEPAD_BUTTON_TRIANGLE=TARA_GAMEPAD_BUTTON_Y

--[[
Gamepad axises.
--]]
TARA_GAMEPAD_AXIS_LEFT_X=0
TARA_GAMEPAD_AXIS_LEFT_Y=1
TARA_GAMEPAD_AXIS_RIGHT_X=2
TARA_GAMEPAD_AXIS_RIGHT_Y=3
TARA_GAMEPAD_AXIS_LEFT_TRIGGER=4
TARA_GAMEPAD_AXIS_RIGHT_TRIGGER=5
TARA_GAMEPAD_AXIS_LAST=TARA_GAMEPAD_AXIS_RIGHT_TRIGGER